sudo: required
services:
  - docker

before_install:
  - docker build -t akli1512/docker-simple-web -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-simple-web"
  env: "DockerSimpleWeb-env "
  bucket_name: "elasticbeanstalk-eu-west-3-345142420557"
  bucket_path: "docker-react-dir"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

